LuxuryWatches/src/main/java/com/luxurywatches/entities/User.java
package com.luxurywatches.entities;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.validator.constraints.Email;

import com.luxurywatches.validator.EmailExistsConstraint;

@Entity
@Table(name = "User", uniqueConstraints = @UniqueConstraint(columnNames = {"email"}))
public class User implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue
	@Column(name = "userId")
	private int userId;
	@Email(message = "Email format is invalid.")
	@Column(name = "email", unique = true)
	@EmailExistsConstraint
	private String email;
	@Column(name = "password")
	private String password;
	@Column(name = "isAdmin")
	private boolean isAdmin;
	@OneToMany(mappedBy = "user")
	private Set<Customer> customers;

	public User() {
		//do not delete
	}

	public User(String email, String password, boolean isAdmin) {
		this.email = email;
		this.password = password;
		this.isAdmin = isAdmin;
	}

	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isAdmin() {
		return isAdmin;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public Set<Customer> getCustomers() {
		return customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}

LuxuryWatches/src/main/java/com/luxurywatches/mb/UserBean.java
package com.luxurywatches.mb;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.hibernate.validator.constraints.Email;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.luxurywatches.DAO.UserDAO;
import com.luxurywatches.entities.Customer;
import com.luxurywatches.entities.User;
import com.luxurywatches.utils.DataConnect;

@ManagedBean(name = "userBean")
@SessionScoped
public class UserBean implements Serializable{

	private static final long serialVersionUID = 1L;
	//email is used to login to system
	@Email(message = "Email format is invalid.")
	private String email2;
	private String password;
	private String dbEmail;
	private String dbPassword;
	private boolean loggedIn;
	private User user = new User();
	private Customer customer = new Customer();
	private List<User> users = new ArrayList<User>();

	private static final Logger LOGGER = LoggerFactory.getLogger(UserBean.class);

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getEmail2() {
		return email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDbEmail() {
		return dbEmail;
	}

	public void setDbEmail(String dbEmail) {
		this.dbEmail = dbEmail;
	}

	public String getDbPassword() {
		return dbPassword;
	}

	public void setDbPassword(String dbPassword) {
		this.dbPassword = dbPassword;
	}

	public boolean isLoggedIn() {
		return loggedIn;
	}

	public void setLoggedIn(boolean loggedIn) {
		this.loggedIn = loggedIn;
	}

	public List<User> getUsers() {
		UserDAO dao = new UserDAO();
		users = dao.findAllUsers();

		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

	/**
	 *
	 * @Register new Customer and account for this customer
	 */
	public String register(){
		UserDAO dao = new UserDAO();

		customer.setUser(this.user);
		//user.setAdmin(false);
		dao.register(this.customer, this.user);

		//take the newly created email via login form
		email2 = user.getEmail();
		//reset data
		user = new User();
		customer = new Customer();

		return "success";
	}

	/**
	 *
	 * @return email and password of User table from database
	 *
	 */
	public void dbData(String email) throws ClassNotFoundException {
		if (email != null) {
			String query = "select email,password from user where email = '" + email + "'";
			Connection connection = null;
			ResultSet resultSet = null;
			Statement statement = null;

			try {
				//open connection
				connection = DataConnect.getConnection();
				if (connection != null) {
					statement = connection.createStatement();
					resultSet = statement.executeQuery(query);
					resultSet.next();
					dbEmail = resultSet.getString("email");
					dbPassword = resultSet.getString("password");
				}
			} catch (SQLException sqle) {
				LOGGER.info("Exception Occured in the process :" + sqle.getMessage());
			}finally {
				if (resultSet != null) {
					try{
						resultSet.close();
					} catch (SQLException e){
						LOGGER.info(e.getMessage());
					}
				}
				if (statement != null) {
					try{
						statement.close();
					} catch (SQLException e){
						LOGGER.info(e.getMessage());
					}
				}
				if (connection != null) {
					DataConnect.close(connection);
				}
			}
		}
	}
	/**
	 *
	 * @Login functional
	 */
	public String login() throws ClassNotFoundException {
		//get email and password from database
		dbData(email2);
		//validate email and password
		if (email2 != null && password != null && email2.equals(dbEmail) && password.equals(dbPassword)) {
			loggedIn = true;
			return "success";
		}
		else if (!email2.equals(dbEmail)){
			// Add View Faces Message
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_INFO,
							"Email doesn't exists",
							"Please register new account"));
			return "fail";
		}
		else {
			// Add View Faces Message
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_WARN,
							"Incorrect Email or Passowrd",
							"Please enter correct email and Password"));
			return "fail";
		}
	}

	/**
	 * add new user account
	 */
	public String addUser() {
		UserDAO dao = new UserDAO();
		dao.addUser(this.user);
		user = new User();
		return "/pages/user/user.jsf?faces-redirect=true";
	}

	/**
	 * get edit action
	 */
	public String editAction(User user) {
		this.user = user;

		return "/pages/user/edit.jsf?faces-redirect=true";
	}

	/**
	 * update user account
	 */
	public String updateUser(){
		UserDAO dao = new UserDAO();
		System.out.println("LOggggggg:   " + user.getEmail() + user.getPassword() + user.isAdmin());
		dao.updateUser(this.user);
		System.out.println("LOggggggg:   " + user.getEmail() + user.getPassword() + user.isAdmin());
		this.user = new User();

		return "/pages/user/user.jsf?faces-redirect=true";
	}

	/**
	 * delete user account
	 */
	public void deleteUser(User user) {
		UserDAO dao = new UserDAO();
		dao.deleteUser(user);
	}
}

LuxuryWatches/src/main/webapp/pages/user/create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

<h:body>
    <ui:composition template="/templates/adminBasePage.xhtml">
        <ui:define name="title">
            <title>Admin | Create User</title>
        </ui:define>
        <ui:define name="body-content">
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <h1>Create New User</h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
                        <li><a href="#">Tables</a></li>
                        <li><a href="#">User Table</a></li>
                        <li class="active">Create User</li>
                    </ol>
                </div>
                <h:form>
                <!-- Main content -->
                <div class="content">
                    <!-- Horizontal Form -->
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">User Form</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form class="form-horizontal">
                            <div class="box-body">
                                <div class="form-group">
                                    <h:outputLabel value="Email" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:inputText value="#{userBean.user.email}" 
                                                     styleClass="form-control"
                                                     style="width:400px"
                                                     id="email" 
                                                     required="true"
                                                     requiredMessage="Email is required"                                                    
                                                     tabindex="1">
                                        </h:inputText>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <div class="form-group">
                                    <h:outputLabel value="Password" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:inputText value="#{userBean.user.password}" 
                                                     styleClass="form-control"
                                                     style="width:400px"
                                                     id="password"
                                                     tabindex="2">
                                         </h:inputText>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <div class="form-group">
                                    <h:outputLabel value="isAdmin" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:selectOneMenu value="#{userBean.user.admin}" styleClass="form-control" style="width:400px">
                                            <f:selectItem itemValue="true" itemLabel="True"/>
                                            <f:selectItem itemValue="fasle" itemLabel="False"/>
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <h:commandButton tabindex="3" 
                                                 value="Save" 
                                                 action="#{userBean.addUser()}" 
                                                 style="width:95px"
                                                 styleClass="btn btn-info btn-flat"/>
                                <h:commandButton tabindex="3" 
                                                 value="Cancel" 
                                                 action="/pages/user/user.jsf?faces-redirect=true"
                                                 style="width:95px"
                                                 styleClass="btn btn-default btn-flat pull-right"/>   
                            </div>
                            <!-- /.box-footer -->
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
                </h:form>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

LuxuryWatches/src/main/webapp/pages/user/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

<h:body>
    <ui:composition template="/templates/adminBasePage.xhtml">
        <ui:define name="title">
            <title>Admin | Edit User</title>
        </ui:define>
        <ui:define name="body-content">
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <h1>Edit User</h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
                        <li><a href="#">Tables</a></li>
                        <li><a href="#">User Table</a></li>
                        <li class="active">Edit User</li>
                    </ol>
                </div>
                <h:form prependId="false">
                <!-- Main content -->
                <div class="content">
                    <!-- Horizontal Form -->
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">User Form</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form class="form-horizontal">
                            <div class="box-body">
                                <div class="form-group">
                                    <h:outputLabel value="User Id" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:inputText value="#{userBean.user.userId}" 
                                                     styleClass="form-control"
                                                     style="width:400px"
                                                     id="userId"      
                                                     disabled="true"                                              
                                                     tabindex="1">
                                        </h:inputText>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <div class="form-group">
                                    <h:outputLabel value="Email" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:inputText value="#{userBean.user.email}" 
                                                     styleClass="form-control"
                                                     style="width:400px"
                                                     id="email" 
                                                     required="true"
                                                     requiredMessage="Email is required"                                                    
                                                     tabindex="1">
                                        </h:inputText>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <div class="form-group">
                                    <h:outputLabel value="Password" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:inputText value="#{userBean.user.password}" 
                                                     styleClass="form-control"
                                                     style="width:400px"
                                                     id="password"
                                                     tabindex="1">
                                         </h:inputText>
                                    </div>
                                </div>
                                <br />
                                <br />
                                <div class="form-group">
                                    <h:outputLabel value="isAdmin" styleClass="col-sm-2 control-label"/>
                                    <div class="col-sm-10">
                                        <h:selectOneMenu value="#{userBean.user.admin}" styleClass="form-control" style="width:400px">
                                            <f:selectItem itemValue="true" itemLabel="True"/>
                                            <f:selectItem itemValue="fasle" itemLabel="False"/>
                                        </h:selectOneMenu>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <h:commandButton tabindex="2" 
                                                 value="Save" 
                                                 action="#{userBean.updateUser()}" 
                                                 style="width:95px"
                                                 styleClass="btn btn-info btn-flat"/>
                                <h:commandButton tabindex="2" 
                                                 value="Cancel" 
                                                 action="/pages/user/user.jsf?faces-redirect=true"
                                                 style="width:95px"
                                                 styleClass="btn btn-default btn-flat pull-right"/>   
                            </div>
                            <!-- /.box-footer -->
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
                </h:form>
            </div>
        </ui:define>
    </ui:composition>
</h:body>
</html>

LuxuryWatches/src/main/webapp/pages/user/user.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

<h:body>
    <ui:composition template="/templates/adminBasePage.xhtml">
        <ui:define name="title">
            <title>Admin | User</title>
        </ui:define>
        <ui:define name="body-content">
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <div class="content-header">
                    <h1>
                        User Table
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
                        <li><a href="#">Tables</a></li>
                        <li class="active">User Table</li>
                    </ol>
                </div>
                <!-- Main content -->
                <div class="content">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box">
                            <div class="box-header">
                                <h3 class="box-title">List User</h3>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <h:form prependId="false"> 
                                <h:dataTable rendered="#{not empty userBean.users}" value="#{userBean.users}" var="u" id="table1" role="grid"
                                             styleClass="table table-bordered table-striped">
                                     <h:column>                 
                                        <f:facet name="header">Id</f:facet>                   
                                        <h:outputText value="#{u.userId}" />
                                     </h:column>
                                     <h:column>
                                        <f:facet name="header">Email</f:facet>
                                        <h:outputText value="#{u.email}" />
                                     </h:column>
                                     <h:column>
                                        <f:facet name="header">Password</f:facet>
                                        <h:outputText value="#{u.password}" />
                                     </h:column>
                                     <h:column>
                                        <f:facet name="header">isAdmin</f:facet>
                                        <h:outputText value="#{u.admin}" />
                                     </h:column>
                                     <h:column>
                                        <f:facet name="header">Options</f:facet>
                                        <h:commandButton styleClass="btn btn-block btn-info btn-flat"
                                                         style="width:95px" 
                                                         value="Edit" 
                                                         action="#{userBean.editAction(u)}" >
                                        </h:commandButton>
                                        <h:commandButton styleClass="btn btn-block btn-danger btn-flat" 
                                                         style="width:95px" 
                                                         value="Delete" 
                                                         type="submit"
                                                         onclick="return confirm('Are you sure to delete it?')" 
                                                         action="#{userBean.deleteUser(u)}" />
                                     </h:column>
                                </h:dataTable>
                                <h:panelGroup rendered="#{empty userBean.users}" styleClass="table table-bordered table-striped">
                                        <p>User account is empty! Please add new user.</p>
                                </h:panelGroup>
                                
                                <h:commandButton styleClass="btn btn-block btn-success btn-flat pull-left" 
                                                 style="width:100px"
                                                 action="/pages/user/create.jsf?faces-redirect=true" 
                                                 value="Create New" /> 
                                </h:form>
                            </div>
                            <!-- /.box-body --> 
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row --> 
                </div>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
        </ui:define>
    </ui:composition>
</h:body>
</html>